[mypy-stim.*]
ignore_missing_imports = True

[mypy-pymatching.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-ldpc.*]
ignore_missing_imports = True

[mypy-dotg.*]
ignore_missing_imports = True

[mypy]
exclude = tests/
disable_error_code = attr-defined